#!/usr/bin/env ruby
ENV['RAILS_ENV'] = $rails_env = ARGV[1] || 'production'
require File.dirname(__FILE__) + '/config/boot'
$command = ARGV[0]
$server_port = case $rails_env
when 'development' : 3000
when 'test' : 3001
when 'production' : 3002
end


case $command
when 'start'
  `script/server -d -p #{$server_port} -e #{$rails_env}`
  `lib/daemons/collector_ctl start  #{$rails_env}`
#  `lib/daemons/indexer_ctl start`
  `lib/daemons/searcher_ctl start`
when 'stop'
  `lib/daemons/collector_ctl stop  #{$rails_env}`
#  `lib/daemons/indexer_ctl stop`
  `lib/daemons/searcher_ctl stop`
  $command = 'killall'
  require 'daemons/manager'
when 'status'
  require 'daemons/manager'
when 'install'
when 'commit'
  `git commit -a -m '#{ARGV[1..-1].join(" ")}'`
when 'update'
  `git pull`
end
