# See http://github.com/eugenebolshakov/app_config
# parsed as ERB, apparently, not YAML?
# accessible as Conf.whatever
# NB must reload app after changing this file

common:
  collector_sync_interval: 5
  hour_daybreak: 4
  rule_searcher: "method:jm,lambda:0.1"
#  rule_searcher: "method:dirichlet,mu:100"
  
development:
  searcher_port: 3200
  
test:
  searcher_port: 3201

production:
  searcher_port: 3202
