development:
  solr:
    hostname: localhost
    port: 3200
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 3201
    log_level: WARNING

production:
  solr:
    hostname: localhost
    port: 3202
    log_level: WARNING
    