#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")
require 'ddl_include.rb'

$command = ARGV[0]
$opt = ARGV[1..-1].map_hash{|e|e.split('=')}
$rails_env = $opt['env'] || ENV['RAILS_ENV'] || 'development'
memcached_pid = File.join(Rails.root, "tmp/pids/memcached_#$rails_env.pid")
#debugger
case $command
when 'start'
  `rake tmp:pids:clear`
  `memcached -d -p #{Conf.memcached_port} -P #{memcached_pid}` if !File.exists?(memcached_pid)
  `rake sunspot:solr:start RAILS_ENV=#$rails_env`
  unless $opt['nosvr']
    `rails server -d -p #{Conf.webserver_port} -e #{$rails_env}`
  end
  #{}`script/collector.sh`
#  `nohup script/runner app/collector/collector_daemon.rb #$rails_env &`
when 'stop'
  File.unlink(memcached_pid)  if File.exists?(memcached_pid)
  `lib/daemons/collector_ctl stop  #{$rails_env}`
  `rake sunspot:solr:stop RAILS_ENV=#$rails_env`
#  `lib/daemons/indexer_ctl stop`
#  `lib/daemons/searcher_ctl stop`
  $command = 'killall'
  require 'daemons/manager'
when 'status'
  require 'daemons/manager'
when 'log'
  puts "==== OUTPUT ===="
  puts `tail log/#{$rails_env}.log`
  puts "==== ERRORS ===="
  puts `tail log/#{$rails_env}_error.log`
when 'install'
when 'commit'
  `git commit -a -m '#{ARGV[1..-1].join(" ")}'`
  `git push`
when 'update'
  `git pull`
when 'test'
  
end
